stages:
  - build
  - test
  - package
  - deploy

build:
  image: openjdk:17-oracle
  stage: build
  before_script:
    - export JAVA_HOME="/usr/lib/jvm/java-17.0.8-openjdk"
  script:
    - chmod +x gradlew
    - ./gradlew clean
    - ./gradlew build
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 10 min

test:
  image: openjdk:17-oracle
  stage: test
  script:
    - ./gradlew test
  
package:
  image: docker:latest
  stage: package
  variables:
    IMAGE_NAME: hanium_iam
  services:
    - docker:dind
  before_script:
    - docker login -u $DOCKER_USERNAME --password-stdin < $DOCKER_PASSWORD
  script:
    - docker build -t $IMAGE_NAME
    - docker push $IMAGE_NAME
  after_script:
    - docker logout

deploy:
  stage: deploy
  tags:
    - docker-runner
  before_script:
    - docker login -u $DOCKER_USERNAME --password-stdin < $DOCKER_PASSWORD
  script:
    - docker stop hanium_iam || true
    - docker rm hanium_iam || true
    - docker rmi hanium_iam || true
    - docker run -d --restart always -p 8080:8080/tcp --name hanium_iam hanium_iam
  after_script:
    - docker logout
  when: on_success
  only:
    - master

  
