version: "3"

services:
  database:
    container_name: iam_db
    image: mariadb
    environment:
      MARIADB_DATABASE: "iam"
      MARIADB_ROOT_PASSWORD: "Qwer1234!"
      TZ: 'Asia/Seoul'
    ports:
      - "3306:3306"

  application:
    container_name: iam_web
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://iam_db:3306/iam
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "Qwer1234!"
    depends_on:
      - database

