/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (5.3.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package kr.or.hanium.iam.api;

import kr.or.hanium.iam.api.model.GroupDto;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
@Validated
@Api(value = "Group", description = "the Group API")
public interface GroupApi {

    /**
     * GET /api/v1/groups
     *
     * @return Success (status code 200)
     */
    @ApiOperation(value = "", nickname = "getGroupList", notes = "", response = GroupDto.class, responseContainer = "List", tags={ "group", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Success", response = GroupDto.class, responseContainer = "List") })
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/api/v1/groups",
        produces = { "application/json" }
    )
    ResponseEntity<List<GroupDto>> getGroupList();

}
